### PR TITLE
[REF] Change the website view in order to show the line options in the correct column of supplier. Added Modal view to manage the purchase order lines

### PR DESCRIPTION
**Pull request by hugho-ad**
DUMMY PR https://github.com/Vauxoo/yoytec/pull/2001
- Modal view added in order  to remove/delete specific order lines from any purchase order in the website console.

image
- Added the feauture of confirmation of any purchase order line from any purchase order.

**VIDEO DEMO**
https://drive.google.com/file/d/0B_jQX2tloXM7NVNqdExkcU5DdUU/view

### CODE REVIEW

**Comment by hugho-ad** [comment]
@nhomar can you help me to review please

**Comment by hugho-ad** [comment]
@moylop260 can you help me to review  this pr please

Regards

**Comment by moylop260** [comment]
The phantomjs test are red. Is this PR or from other one?

**Comment by hugho-ad** [comment]
They are flaky 
image
https://travis-ci.com/Vauxoo/yoytec/jobs/54068614

**Pull request merged**
